"""
Project Intelligence — Claude Code plugin and npm package checks.
The plugin files are generated by installer/build-plugin.js; these tests fail if
they are stale, if a skill would not load, or if records would be written outside
the user's project.
Zero external dependencies (Python standard library only).
"""

import json
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _frontmatter(text):
    """Minimal parse of the top-level scalar keys we rely on (name, description)."""
    if not text.startswith("---\n"):
        return None
    block = text[4:text.index("\n---", 4)]
    out = {}
    for line in block.splitlines():
        m = re.match(r"^([A-Za-z][\w-]*):\s?(.*)$", line)
        if m:
            value = m.group(2).strip()
            if value.startswith('"'):
                value = json.loads(value)
            out[m.group(1)] = value
    return out


class TestPluginFiles(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if shutil.which("node") is None:
            raise unittest.SkipTest("node is not installed")
        out = subprocess.run(
            ["node", "-e", "const b=require('./installer/build-plugin.js');console.log(JSON.stringify({m:b.manifest,k:b.marketplace,a:b.askCommand,c:b.COUNCIL_MEMBER_MD}))"],
            cwd=ROOT, capture_output=True, text=True, check=True).stdout
        cls.built = json.loads(out)

    def test_generated_files_are_up_to_date(self):
        on_disk = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
        self.assertEqual(on_disk, self.built["m"], "Run `npm run build:plugin`")
        self.assertEqual(json.loads((ROOT / ".claude-plugin" / "marketplace.json").read_text()), self.built["k"])
        self.assertEqual((ROOT / "plugin-skills" / "ask" / "SKILL.md").read_text(), self.built["a"])
        self.assertEqual((ROOT / "plugin-agents" / "council-member.md").read_text(), self.built["c"])

    def test_council_member_agent_is_read_only(self):
        fm = _frontmatter(self.built["c"])
        self.assertEqual(fm["name"], "council-member")
        tools = [t.strip() for t in fm["tools"].split(",")]
        self.assertNotIn("Edit", tools)
        self.assertNotIn("Write", tools)
        self.assertNotIn("Bash", tools)
        self.assertEqual(self.built["m"]["agents"], ["./plugin-agents/council-member.md"])

    def test_manifest_matches_package(self):
        pkg = json.loads((ROOT / "package.json").read_text())
        m = self.built["m"]
        self.assertEqual(m["version"], pkg["version"])
        self.assertEqual(m["license"], pkg["license"])
        self.assertRegex(m["name"], r"^[a-z0-9]+(-[a-z0-9]+)*$")
        self.assertNotRegex(m["name"], r"^(claude|anthropic)")

    def test_component_paths_exist_inside_plugin(self):
        m = self.built["m"]
        for rel in m["skills"]:
            self.assertTrue(rel.startswith("./"))
            self.assertTrue((ROOT / rel).is_dir(), rel)
        args = m["mcpServers"]["project-intelligence"]["args"]
        self.assertEqual(args[0], "${CLAUDE_PLUGIN_ROOT}/adapters/mcp/server.py")
        self.assertTrue((ROOT / "adapters" / "mcp" / "server.py").exists())
        self.assertEqual(self.built["k"]["plugins"][0]["source"], "./")
        self.assertEqual(self.built["k"]["plugins"][0]["name"], m["name"])

    def test_every_skill_loads_by_name(self):
        dirs = [p for base in ("skills", "vendor/skills", "plugin-skills") for p in (ROOT / base).iterdir() if (p / "SKILL.md").exists()]
        names = []
        for d in dirs:
            with self.subTest(skill=str(d.relative_to(ROOT))):
                fm = _frontmatter((d / "SKILL.md").read_text(encoding="utf-8"))
                self.assertIsNotNone(fm, "missing frontmatter")
                self.assertEqual(fm.get("name"), d.name)
                self.assertTrue(fm.get("description"))
                self.assertLessEqual(len(fm["description"]), 1024)
                names.append(fm["name"])
        self.assertEqual(len(names), len(set(names)), "skill names must be unique across the plugin")

    def test_ask_skill_calls_plugin_copy_of_cli(self):
        text = self.built["a"]
        self.assertIn("$ARGUMENTS", text)
        self.assertIn('node "${CLAUDE_PLUGIN_ROOT}/bin/cli.js" ask', text)

    def test_package_bin_and_files(self):
        pkg = json.loads((ROOT / "package.json").read_text())
        self.assertEqual(pkg["name"], "@sahasbelbase/project-intelligence")
        bin_path = ROOT / pkg["bin"]["project-intelligence"]
        self.assertTrue(bin_path.exists() and os.access(bin_path, os.X_OK))
        for f in (".claude-plugin", "plugin-skills", "vendor", "core", "adapters", "bin", "installer"):
            self.assertIn(f, pkg["files"])


class TestRunsFromUserProject(unittest.TestCase):
    def test_commands_and_records_use_the_current_folder(self):
        if shutil.which("node") is None:
            self.skipTest("node is not installed")
        record = json.loads((ROOT / "memory" / "council-briefs" / "dec-orchestrator-council-integration.json").read_text())
        session = {
            "councilId": record["councilId"], "task": record["task"],
            "convened": [m["personaId"] for m in record["convened"]],
            "round1": record["rounds"]["independent"], "challenges": record["rounds"]["challenges"],
            "revisions": record["rounds"]["revisions"],
            "synthesis": {**record["brief"], "decisionId": "dec-plugin-check", "dissent": []},
        }
        with tempfile.TemporaryDirectory() as tmp:
            Path(tmp, "session.json").write_text(json.dumps(session))
            cli = str(ROOT / "bin" / "project-intelligence")
            res = subprocess.run(["node", cli, "council", "record", "session.json"], cwd=tmp, capture_output=True, text=True)
            self.assertEqual(res.returncode, 0, res.stderr)
            self.assertTrue(Path(tmp, "memory", "council-briefs", "dec-plugin-check.json").exists())
            self.assertFalse((ROOT / "memory" / "council-briefs" / "dec-plugin-check.json").exists())
            res = subprocess.run(["node", cli, "ask", "Redesign the settings page navigation"], cwd=tmp, capture_output=True, text=True)
            self.assertEqual(res.returncode, 0, res.stderr)
            self.assertIn("bin/cli.js\" council prompt design", res.stdout)
            self.assertNotIn("python3 -m core", res.stdout)


if __name__ == "__main__":
    unittest.main()


class TestInvocation(unittest.TestCase):
    """Installed files must not point into npm's temporary npx cache."""

    def _call(self, expr):
        if shutil.which("node") is None:
            self.skipTest("node is not installed")
        out = subprocess.run(["node", "-e", f"const i=require('./installer/invocation');console.log(JSON.stringify({expr}))"],
                             cwd=ROOT, capture_output=True, text=True, check=True).stdout
        return json.loads(out)

    def test_npx_cache_uses_npx(self):
        root = "/home/u/.npm/_npx/abc123/node_modules/@sahasbelbase/project-intelligence"
        self.assertEqual(self._call(f"i.cliInvocation({json.dumps(root)})"), "npx -y @sahasbelbase/project-intelligence")
        entry = self._call(f"i.mcpServerEntry({json.dumps(root)}, '/home/u/app')")
        self.assertEqual(entry["command"], "npx")
        self.assertEqual(entry["args"][-1], "mcp")

    def test_normal_install_uses_absolute_path(self):
        self.assertEqual(self._call("i.cliInvocation('/opt/pi')"), 'node "/opt/pi/bin/cli.js"')
        self.assertEqual(self._call("i.mcpServerEntry('/opt/pi', '/home/u/app')")["args"], ["/opt/pi/adapters/mcp/server.py"])
        self.assertEqual(self._call("i.mcpServerEntry('/opt/pi', '/opt/pi')")["args"], ["adapters/mcp/server.py"])
